inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - vendor/**/*
    - example/**/*
  TargetRubyVersion: 2.4

Layout/EmptyLinesAroundArguments:
  Enabled: false

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/ClassLength:
  Max: 300

Metrics/LineLength:
  Max: 120
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Max: 26
  Exclude:
    - spec/**/*

Metrics/PerceivedComplexity:
  Max: 11

Naming:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false
